; =================================
; Сессии
; =================================
; Храним сессии в отдельной папке
session.save_handler = files
session.save_path = "/tmp/php-sessions"

; Время жизни сессии на сервере (2 часа)
session.gc_maxlifetime = 7200
session.gc_probability = 1
session.gc_divisor = 1000

; Cookie сессии
session.cookie_lifetime = 0
session.cookie_httponly = 1
session.cookie_samesite = Strict

; Строгая и безопасная работа с сессиями
session.use_strict_mode = 1
session.use_only_cookies = 1
session.use_trans_sid = 0
; session.cookie_secure = 1 для прода

; =================================
; Ошибки
; =================================
display_errors = Off
display_startup_errors = Off
log_errors = On
error_log = /proc/self/fd/2
error_reporting = E_ALL

; =================================
; Время
; =================================
date.timezone = Europe/Moscow

; =================================
; Базовая безопасность
; =================================
expose_php = Off

; Жёсткий таймаут выполнения скрипта PHP-FPM
hard_timeout = 10